* Chapter 5
[On their way from Thusis to Davos to meet someone]
[Andreas is the local contact]
[How do we know the train is safe?]

We said farewell to Andreas at the platform and climbed aboard the train. We found seats by the window in a quiet part of the carriage where we could sit without anyone disturbing us. There was no one else in the carriage, save for an elderly couple engrossed in their newspapers at the far end. I lifted my rucksack onto the overhead rack and sat down opposite Ellie. She hadn't spoken to me since we'd left the hostel that morning.

There was a clanking sound, and with a jolt the train started to pull away from the station. We sat in silence for some time as the scenery started to roll past. As the train started to pick up speed, at the same time I could feel my racing thoughts finally begin to slow down. Ellie looked across at me and brushed a lock of hair out of her eyes.
'Do you think they'll listen to us?'
'They don't have a choice. We know who is behind everything, and the evidence is undeniable. I only worry that Jackson will get there before we do.'
'Yes, and if he does? What happens then? What about everything we've worked for? What happens to us?'
She held my gaze for a long time. I could see the fury in her eyes. Fury at the web we'd found ourselves caught in, and fury that I'd dragged her into it along with me. I couldn't answer her. Finally, Ellie bit her lip and then looked away. She knew as well as I did that it wasn't worth thinking about the consequences if we failed.
'I'm sorry, Ellie.'
She raised her head again and looked at me with danger in her eyes.
'Don't.'
A momentary twitch in one eye hinted at the level of tiredness and frustration she was feeling, but she continued to look straight at me. I tried again.
'No, really, I'm sorry.'
'And I said don't. Yes, I'm mad at you. But I understand why you had to do this. And I'm hardly going to let you take all the credit, am I?'
With a forceful sigh, she turned her head and looked out of the window. I continued to look at her for a few moments. Her dark hair fell across the side of her face, obscuring her eyes from mine and leaving her profile in shadow. I realised I'd found a level of admiration for her, and it gave me a fresh pang of regret to think that I'd put her in such danger only to suit my own ego. Finally, I let my gaze join hers outside the window. We'd left the town far behind us and were climbing steadily through a thick pine forest. The trees were over twenty metres tall, towering above us with branches heavy with snow, like white icing dripping off thick, dark sponge cake. Although it was the middle of the day, the density of the forest blocked out most of the light from the low winter sun, so it appeared as if it was already dusk. It felt like it would be so easy to disappear here, at least for a while, and no one would even notice. As the train groaned and screeched around the tight curves, the landscape began to fall away on one side into a deep ravine. I caught glimpses of a frothing white stream in the gorge fifty metres below. After a while I saw a place where the stream had backed up against a pile of rocks which had fallen down the valley, blocking its path. Ellie saw me looking at the picture far below.
'It's funny, isn't it?', she said, breaking the silence. 'It seems so easy at first to stop a stream. A few small rocks will do the trick. But eventually the water always wins. It's inevitable.' She gave a bitter laugh and gestured at the ravine below us with her hand. 'I mean, in the end, that tiny current carved out this whole gorge. You can't stop it.'
She tore her gaze from the window and looked at me with sadness in her eyes.
'Who are we, trying to drop a few small rocks into the stream and pretending to ourselves that we can change the inevitable?'

Before long, we were atop a ledge looking down onto the forest, and the train began to hug the cliff in a long, banking curve. A solid wall of rock to the other side provided a welcome feeling of security. The gentle rhythm of the train rocking along the narrow tracks and the peacefulness of the landscape outside the window were like a soothing caress, and soon my mind began to meander like a kaleidoscope from one thought to the next, each thought never resting or completely taking form. I considered what we'd left behind, whether we'd ever be welcome in our own country again. Would they hold us as traitors and hunt us down? I thought about Jen and Bill, and how they'd supported us all the way to the end. How many more would lose everything over this before the world sat up and took notice?

I must have lost myself in thought for at least twenty minutes when the sharp rattling of a steel bridge penetrated my consciousness and shocked me to my senses. As I looked down, I could see that we were crossing over a waterfall that gushed out of a cleft in the rock and tumbled down to the valley below. Long columns of ice clung to the rock either side of the waterfall, and the spray seemed to freeze in the air.
'We need to think about our backup plan', I said, trying to gather my thoughts into action.
Ellie jolted in her seat, then sat up and turned to face me with an expression of momentary confusion.
'Sorry, I must have dozed off. What did you say?'
'It's okay. I was saying we should think about a backup plan in case <?> refuses to see us tomorrow.'
Ellie narrowed her eyes in thought. She opened her mouth to reply when there was a sudden ear-splitting squealing of steel on steel. The train shuddered to a halt.
'Shit! What was that?' exclaimed Ellie as she gripped the sides of her seat. I could see she was feeling as tense as I was. The elderly couple at the far end of the carriage had put down their newspapers and were staring at us.
I craned my neck to the window, trying to see what might have caused our abrupt stop. 'I can't see anything. Hold on.'
I stood up and pulled down the window so I could put my head outside for a clearer view. We were still surrounded by forest, but a large snowy clearing lay a short way beyond the tracks. The bright red carriages of the train curved ahead of us into the distance like a crimson intruder amongst the muted greens, greys and white of the wintry land surrounding us. A subtle movement near the front of the train caught my attention, and a few moments later a brown-coated figure sprang down from the tracks and into the clearing. As it flashed towards the trees at the far side, it stopped and glanced back at us before melting into the darkness.
'It's only a deer,' I said, smiling at Ellie and trying to hide the shaking in my hands as I sat down and closed the window. 'It must have wandered onto the tracks in front of the train. Nothing to worry about.'
Ellie gave me a weak smile in return, but I could read the fear in her eyes. How much longer could we live with this tension before one of us snapped?

Less than a minute passed before we were on the move again. I checked my watch. We should be arriving in Filisur station shortly, where we would change for a train to Davos and the fate that awaited us. Out of the window a dramatic viaduct rose into view ahead of us. Built from solid grey stone, it swept in an elegant arc, carrying the railway line on five pillars high above the foaming river below. It was both beautiful and imposing at the same time, seemingly cut from the same stone as the mountains themselves. At the end of the viaduct, the railway plunged into the gaping black hole of a tunnel high up in the face of a cliff.
'Look Ellie, we're coming up to the Landwasser viaduct', I said, trying to say something to break the tension.
'It's beautiful', she said, leaning over to get a better look. 'I saw it on TV once.' She smiled, but as soon as the smile reached her lips, her face froze into an expression of fear.
'What is it, Ellie?'
'Oh my god.'
I turned and looked behind me, where I could see two tall figures in long coats in the carriage behind ours. They were making their way towards us.
'How did they find us?', she asked in a voice laced with panic. 'We checked the whole train before we got on' <How do we know the train was safe?>
With a chill, realisation dawned.
'The deer! When the train stopped... they must have been there, waiting. Most likely they chased it onto the track as a way to stop the train.'

[Landwasser struggle]
[Grab the rucksack!]



