* TODOs
** TODO Is 30 years enough for extinction, desertification?
** TODO What does AI look like in 2050s?
** TODO Describe characters fully (not immediately in book!)
* Settings
** 2050s
*** General
   After events of the Great Extinction
   AI has advanced to be prevalent
   "The central European desert"
*** Technology
    Self-driving cars
    Autonomous drones
** 2010s
*** Birmingham
*** Switzerland
    Graubünden, WEF
* Characters
  General guidelines: https://www.thecreativepenn.com/2012/10/01/characters/
  Nationality, social status and job/occupation.
  Beliefs, values, preoccupations, superstitions, preferences, fears or phobias (Is he/she afraid of the dark? Or maybe spiders?) and why they fear that specific thing.
  Friends/allies, enemies, any family he/she has, any lover or crush, etc.
  Particular talents (maybe he/she is good at juggling), any movements/protests he/she is involved in (describe the movement/protest and its purpose), and past/childhood (maybe he/she used to be a warrior or a bank-robber), etc.
  Hobbies/things he/she likes to do for fun.
  Describe his/her current home (in full detail) and past/childhood home.

  Describe the character's personality in detail. Is he/she loud and flamboyant, or more the quiet introvert? Does he/she stand for his/her beliefs? Is he/she shy, or in-your-face? You want your readers to know exactly what kind of person your character is, if required.
  Of personality traits, which are the best? They are all great for working with as a writer, but you must choose a reasonable selection that best fits your character––don't try to overwhelm the character with an unlikely combination of many traits.
  Don't give the character merely neutral or good traits. Also spice it up with the vices and weaknesses. Your character is best if presented as imperfect (in actions, appearance or personality). Your character can make mistakes, have bad habits, and possess little interesting quirks. This is what makes the character interesting. For example: Is he so nice that he gets taken advantage of? Or is she so pretty that it goes to her head? Is she such a tomboy that the guys don't mind including her in guy's night out?
** 2050s
*** Michi Brunwald
    Forest ranger?
    From Valais
*** Ellie Carpenter
    Lab researcher in Birmingham
** 2010s
* Style
** General principles
   Try to teach about realistic use of AI and technology in the future
   High Tech as well as humanity -- not just gadgetry to save the day
** Potential writing styles
*** 1. Set in 2050s with flashbacks to events in 2010s
    Possible to set a series of books in the 2050s  
*** 1a. Parallel intertwined storylines in 2050s and 2010s
    Two characters in the 2050s adapting to change in the new world
    "Unrelated" characters in the 2010s
      - but their paths intertwine throughout
*** 2. Multiple linear books
    Like Hangman's Daughter, follow family members through generations
    2020s, 2050s (with multiple adventures), ...?
    More opportunity to play with technology development
** Potential narrator perspectives
*** 1. 3rd person
    Can get inside multiple characters
*** 2. 1st person
    Can relate to the narrator very well
    But the narrator may change over the series of books
*** 3. 3rd person but focussed by chapter / timeline
    Like Game of Thrones, different separated characters take the main role in 
    each chapter
* Plot
** Storyline 1: 2010s
   Melting permafrost exposes spores of fungus which grew in ancient soil 4 
   mio years ago. It attacks grasses, preventing photosynthesis and killing 
   it. No big problem since 4 mio years ago it lived in equilibrium with 
   bacteria that consumed the fungus, but now the fungus can spread 
   unchecked. It is naturally resistant to anti-fungal medications and is soon
   located in crops around the region.
    
   The ecological and societal impacts if it spreads unchecked will be huge:
   food shortages, mass extinctions, mass migrations.
    
   Ellie is a biologist in a lab in Birmingham, UK. She realises that in the 
   ancient world, this fungus would not have spread unchecked. There must be 
   an organism which kept it in check -- she starts a search for such an 
   organism (fungivore) but needs to find where the fungus originated from.

   A global pharmaceutical company is working along the same lines but wants 
   to patent the cure to have a monopoly on the treatment. They pop up in the 
   permafrost areas and don't take kindly to Ellie's investigation. Ellie 
   believes that their approach to synthesise the mechanism from the bacteria 
   will not work and she has the correct approach, but they start to send
   sinister people to try to disrupt her work and scare her off. Time is 
   running out.

   The world starts to notice crops dying. Ellie realises that the world 
   needs to hear about her work so she plans to address world leaders at
   the WEF in Switzerland. She meets Michi Brunwald, a botanist in Zürich. He 
   has some ideas based on xyz that he noticed in his work.

   Part of this storyline involves real scientific research to locate the 
   source of the outbreak in the permafrost, and to search the habitat for 
   the consuming bacteria which can be re-animated.
** Storyline 2: 2050s
   The earth is massively desertified. Plants can only be grown in huge 
   bio-domes, society is upheaved. Dust storms ravage the cities, almost no 
   one lives outside of the cities now. Some remote islands are kept as 
   military-guarded clean-areas as "bio reserves". AI plays a major role in 
   trying to keep civilisation functioning.
** Outline
*** < >, 2057
    Sandstorm in < >
*** Siberia, 2005
    Melting permafrost exposes fungus which grew in pre-ice-age soil
    No living matter seen in its radius
    Spores travel on the wind
*** Birmingham, 2013
    Ellie working in the lab as ecologist
