* Death of grass
** Oxygen depletion
   https://www.quora.com/What-would-happen-if-all-the-worlds-grass-died-permanently
   I won’t write in full details but will highlight some important points.

Grass comes under the category of monocots so the have iso-bilateral leaves hence equal number of stomata are present on both the dorsal and ventral sides. Therefore maximum amount of gaseous exchange is done by monocots especially when it comes to grasses. Hence, there will be low percentage of OXYGEN in the atmosphere.

When it comes to Ecology, we will obviously see disturbance in the food-chain leading to extinction of insects and related species.
** Food chain extinction
https://www.quora.com/What-would-happen-if-all-the-worlds-grass-died-permanently
I would say the human race would end ! With us, several animal species would also perish. I might sound crazy ;) Literally, without grass, there’s nothing. Here is why I say so…

They are the starters in every ecosystems due to the capability to grow and sustain in every possible landscape, be it a plain, mountain, desert, rain forest, tundra even in the sea beds! They are the ultimate survivors in the plant kingdom and due to this reason, they feed the entire world !


I would rather call them the phoenix ! They too rise from the ashes !

As we all know the whole world lives on two main food sources, wheat and rice (and even maize). Obviously, they are all grasses !

Millets, oats, barley, sugar-cane are also grasses.

They provide almost all the sources of food to humans, our cattle, poultry and other animals in our farms. So, no rice, no bread, no sugar, no sandwich, no burgers, no pizzas and the list goes on…

Grasses cover a huge percent of land area. Grasslands in the wider sense are among the largest ecosystems in the world. Their area is estimated at 52.5 million square kilometres, or 40.5 percent of the terrestrial area (excluding Greenland and Antarctica) They are found in every continent but with different names,

U.S. Midwest, they are called prairies
South America, they are called pampas
Central Eurasian grasslands are called steppes
Africa they are called savannas
All these lands would become plain deserts without grasses. There would be huge deserts in every continent without grasses and there would be huge dust storms in our cities (there are no grass to hold the soil).

Besides feeding the world, both agricultural and wild, grasses offer huge amounts of other things to us. Some of that include, drink (beer, whisky), pasture for livestock, thatch, paper, fuel, clothing, insulation, construction, sports turf, basket weaving and many others.

Another important grass is the Bamboo. It has been used by humans in numerous ways in each and every civilization. Bamboos are sometimes harder than steel. So it is used in construction of homes, bridges, fences, make utensils, etc. The Chinese, Japanese and the Indians would suffer the most without bamboos ! We even won’t have the cute Pandas as their food comprises only of bamboo shoots. Bamboo produces seeds similar to rice which is also used as a food in India (There are dishes with bamboo rice in Tamil Nadu!).

P.S.: No beauty without grasses in the lawns of our gardens and parks :(

My answer my be a bit unordered because I have managed to accummulate all the points that came to my mind after I read this question!
** Animal migration
** Human migration
*** Political problems
